import { Geist, Geist_Mono } from "next/font/google";
import "@fontsource/montserrat"; // Defaults to weight 400
import "@fontsource/montserrat/400.css"; // Specify weight
import "@fontsource/montserrat/400-italic.css"; // Specify weight and style
import "./globals.css";
import { headers } from "next/headers";
import ContextProvider from "../context";
import { AuthProvider } from "../context/AuthContext";
import { ToastContainer } from "react-toastify";
import ThemeProviderClient from "@/theme/ThemeProviderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sproutly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookies = (await headers()).get("cookie");
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/Favi.svg" />
      </head>
      <body
        className={`backgroundImg ${geistSans.variable} ${geistMono.variable}`}
      >
        <ContextProvider cookies={cookies}>
          <AuthProvider>
            <ThemeProviderClient>{children}</ThemeProviderClient>
            <ToastContainer />
          </AuthProvider>

        </ContextProvider>
      </body>
    </html>
  );
}
