import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sproutly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/Favi.svg" />
      </head>
      <body className={`backgroundImg ${geistSans.variable} ${geistMono.variable}`}>
        <div className="app-container" style={{ display: 'flex' }}>
          <aside >
            <Sidebar />
          </aside>

          <div className="main-layout" style={{ padding: "32px", flex: 1 }}>
            <main className="content">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}



