import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import { headers } from "next/headers";
import ContextProvider from "../../context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sproutly",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookies = (await headers()).get("cookie");

  return (
    <html lang="en">
      <body
        className={`backgroundImg ${geistSans.variable} ${geistMono.variable}`}
      >
        <ContextProvider cookies={cookies}>
          <div className="app-container" style={{ display: "flex" }}>
            <aside>
              <Sidebar />
            </aside>

            <div className="main-layout" style={{ padding: "32px", flex: 1 }}>
              <main className="content">{children}</main>
            </div>
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
